spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
  data:
    mongodb:
      database: payment
      uri: mongodb+srv://Frizzer:Giraf008@cluster0.mtbpt95.mongodb.net/?retryWrites=true&w=majority
kafka:
  bootstrap: localhost:9092
  topic:
    payment: CREDIT_PAYMENT
server:
  port: 7002
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE