spring:
  data:
    mongodb:
      database: client
      uri: mongodb+srv://Frizzer:Giraf008@cluster0.mtbpt95.mongodb.net/?retryWrites=true&w=majority
  kafka:
    consumer:
      auto-offset-reset: earliest
kafka:
  bootstrap: localhost:9092
server:
  port: 7000
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
